services:
    postgres:
        env_file: .env
        image: postgres:18.2
        ports:
            - '${POSTGRES_PORT}:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        command: postgres -c log_statement=all -c log_connections=on -c log_disconnections=on
        volumes:
            - pgdata:/var/lib/postgresql

    temporal:
        image: temporalio/auto-setup:1.25
        ports:
            - '7233:7233'
        environment:
            DB: postgres12
            DB_PORT: 5432
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PWD: ${POSTGRES_PASSWORD}
            POSTGRES_SEEDS: postgres
        depends_on:
            - postgres

    temporal-ui:
        image: temporalio/ui:2.31.2
        ports:
            - '8233:8080'
        environment:
            TEMPORAL_ADDRESS: temporal:7233
            TEMPORAL_CORS_ORIGINS: http://localhost:3000
        depends_on:
            - temporal

    loki:
        image: grafana/loki:3.7.1
        ports:
            - '3100:3100'
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - lokidata:/var/lib/loki

    tempo:
        image: grafana/tempo:2.7.2
        ports:
            - '3200:3200'
            - '4318:4318'
        command: -config.file=/etc/tempo/config.yaml
        volumes:
            - ./tempo/config.yaml:/etc/tempo/config.yaml
            - tempodata:/var/tempo

    prometheus:
        image: prom/prometheus:v3.1.0
        ports:
            - '9090:9090'
        command:
            - --config.file=/etc/prometheus/config.yaml
            - --web.enable-otlp-receiver
            - --enable-feature=native-histograms
        volumes:
            - ./prometheus/config.yaml:/etc/prometheus/config.yaml
            - prometheusdata:/prometheus

    grafana:
        image: grafana/grafana:12.4.2
        ports:
            - '3001:3000'
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
            GF_INSTALL_PLUGINS: grafana-lokiexplore-app
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - grafanadata:/var/lib/grafana
        depends_on:
            - loki
            - tempo
            - prometheus

volumes:
    pgdata:
    lokidata:
    grafanadata:
    tempodata:
    prometheusdata:
