export enum DOMAIN_ERROR_CODE {
    LINE_ITEMS_EMPTY,
    LINE_ITEMS_DIFFERENT_CURRENCIES,
    LINE_ITEMS_DUPLICATE,
    LINE_ITEM_NOT_INTEGER_QUANTITY,
    LINE_ITEM_NOT_POSITIVE_QUANTITY,
    CALENDAR_DATE_INVALID_FORMAT,
    MONEY_MINOR_UNITS_NOT_INTEGER,
    MONEY_MINOR_UNITS_NOT_GTE_ZERO,
    CURRENCY_NOT_ISO_4217,
    MONEY_CURRENCIES_NOT_EQUAL
}